namespace Prototype2WebApi.Enums
{
    public enum SystemErrorCodes
    {
        CustomerNotValid,
        CustomerDuplicate,
        CustomerCreationFailed,
        PostedStoryDuplicate,
        ScheduleCreationFailed,
        AuthenticationFailed,
        BankAccountNotValid,
        BankAccountCreationFailed,
        BankAccountNotValidForTransaction,
        InsufficientFundsForTransaction,
        SchedueNotValid,
        PostedStoryFailed,
        FollowerNotValid,
        FollowerDuplicate,
        FollowerCreationFailed,
        AvatarNotValid,
        AvatarDuplicate,
        AvatarCreationFailed,
        FamilyGroupNotValid,
        FamilyGroupDuplicate,
        FamilyGroupCreationFailed,
        FamilyStatusNotValid,
        FamilyStatusDuplicate,
        FamilyStatusCreationFailed,
        AuthenticationNotValid,
        AuthenticationDuplicate,
        AuthenticationCreationFailed
    }
}
